name: CI Pipeline

on:
  release:
    types: [published]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup go
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.17

    - name: Build
      run: |
        cd warehouse/web
        yarn install && yarn build
        cd ..
        go build main.go

    - name: Test backend
      run: |
          cd warehouse
          go install github.com/onsi/ginkgo/ginkgo@latest
          ginkgo -r -keepGoing .


    - name: Test frontend
      run: |
        cd warehouse/web
        elm-test
    
    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        build_dir: warehouse/web
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
